$c8wildflyfolder = "C:\Program Files\Centric Software\C8\Wildfly"
$server = "win16-sql19" #Changing this will reflect in DB backup only
$RootFolder = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$StandarddbbackupDir = Join-Path $RootFolder "Db Backup" 
$dbbackupDir = Join-Path $RootFolder "Db Backup"
$backupFolder = Join-Path $RootFolder "File Backup\Backup_$(Get-Date -Format "dd-MM-yyyy_HH-mm-ss")"
$keytoolFolder = Join-Path $c8wildflyfolder "standalone\configuration\pkcs_stores"
$pkcsPath = Join-Path $c8wildflyfolder "standalone\configuration\pkcs_stores\"
$piConfigurationPropertiesFile = Join-Path $c8wildflyfolder "standalone\configuration\pi-configuration.properties"
$StandalonePixmlFile= Join-Path $c8wildflyfolder "standalone\configuration\standalone-pi.xml"
$StandalonePimssqlxmlFile=Join-Path $c8wildflyfolder "standalone\configuration\standalone-pi-mssql.xml"
$binFolder = Join-Path $c8wildflyfolder "bin" 
$StandaloneConfBatFile=Join-Path $binFolder "standalone.conf.bat" 
$pfxUtilsPath = (Join-Path $RootFolder "\Utils\C8.pfx")